### ISSUE TITLE
Decoding nested struct works in debug (default) build, fails in release build

### ISSUE THREAD

**Issue by kookman** [andrejp88/toml-foolery#1]
I'm having a problem decoding the following TOML on ARM (32 bit).
``` toml
[[tanks]]
mqttTopic = "sensors/MusicRoomTank/depthCm"
tankDepthCm = 48
microsToCmFactor = 55.0

[[tanks]]
mqttTopic = "sensors/MainTank/depthCm"
tankDepthCm = 200
microsToCmFactor = 55.0
```

The code (reduced) to decode:
``` d
/+ dub.sdl:
    name "tomltest"
    dependency "toml-foolery" version="~>1.0"
+/

import toml_foolery;
import std.stdio;
import std.file;

struct Config
{
    TankSensor[] tanks;

    struct TankSensor
    {
        string mqttTopic;
        int tankDepthCm;
        float microsToCmFactor;
        int countMeasures;
        int runningTotal;
    }
}


void main()
{
    auto config = readText("tankconfig.toml").parseToml!Config;
    writefln("Tanks config length: %s, content: %s", config.tanks.length, config.tanks);
}
```

The same code/config works fine on x86_64.
